const speakItTypes = {
    SET_WORDS: 'mainGame/SET_WORDS',
    SET_CURRENT_WORD_NUMBER: 'mainGame/SET_CURRENT_WORD_NUMBER',
    INCREASE_CURRENT_WORD_NUMBER: 'mainGame/INCREASE_CURRENT_WORD_NUMBER',
    SET_AUTO_SOUND_ENABLED: 'mainGame/SET_AUTO_SOUND_ENABLED',
    SET_CORRRECT_WORD_PROVIDED: 'mainGame/SET_CORRRECT_WORD_PROVIDED',
    SET_INCORRRECT_WORD_PROVIDED: 'mainGame/SET_INCORRRECT_WORD_PROVIDED',
    SET_INITIAL_STATE: 'mainGame/SET_INITIAL_STATE',
    SET_IS_TRANSLATION_ENABLED: 'mainGame/SET_IS_TRANSLATION_ENABLED',
    SET_LEARNED_WORDS_NUMBER: 'mainGame/SET_LEARNED_WORDS_NUMBER',
    ADD_NEW_WORD: 'mainGame/ADD_NEW_WORD',
};

export default speakItTypes;
