const types = {
    SET_TOKEN: 'SET_TOKEN',
    CLEAR_TOKEN: 'CLEAR_TOKEN',
    SET_USER_ID: 'SET_USER_ID',
    CLEAR_USER_ID: 'CLEAR_USER_ID',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_ERROR: 'CREATE_USER_ERROR',
    LOGGED_IN: 'LOGGED_IN',
    LOGIN_ERROR: 'LOGIN_ERROR',
};

export default types;
