const statisticsTypes = {
    FETCH_STATISTICS_PENDING: 'statistics/FETCH_STATISTICS_PENDING',
    FETCH_STATISTICS_SUCCESS: 'statistics/FETCH_STATISTICS_SUCCESS',
    FETCH_STATISTICS_FAILED: 'statistics/FETCH_STATISTICS_FAILED',
    SET_DEFAULT_STATISTICS: 'statistics/SET_DEFAULT_STATISTICS',
    ENCREASE_LEARNED_WORDS_NUMBER: 'statistics/ENCREASE_LEARNED_WORDS_NUMBER',
    SET_MINIGAMES_STATISTICS: 'statistics/SET_MINIGAMES_STATISTICS',
    INC_SUCCESS: 'statistics/INC_SUCCESS',
    INC_ERRORS: 'statistics/INC_ERRORS',
    INC_NEW_WORD: 'statistics/INC_NEW_WORD',
};

export default statisticsTypes;
