const puzzleTypes = {
    SET_PAGINATION: 'SET_PAGINATION',
    SET_LEVEL_PASSED: 'SET_LEVEL_PASSED',
    SET_OPTIONS_PASSED: 'SET_OPTIONS_PASSED',
    SET_DATA: 'SET_DATA',
    SET_CURRENT_LINE: 'SET_CURRENT_LINE',
    SET_CURRENT_GUESSED_WORDS: 'SET_CURRENT_GUESSED_WORDS',
    SET_GUESSED_ARRAYS: 'SET_GUESSED_ARRAYS',
    SET_CURRENT_SHUFFLED: 'SET_CURRENT_SHUFFLED',
    SET_CURRENT_ORIGINAL_ARRAY: 'SET_CURRENT_ORIGINAL_ARRAY',
    SET_SOUND_LINK: 'SET_SOUND_LINK',
    SET_DIFFERENCE_INDEXES: 'SET_DIFFERENCE_INDEXES',
    SET_GAME_IN_PROGRESS: 'SET_GAME_IN_PROGRESS',
    SET_READY_FOR_REVIEW: 'SET_READY_FOR_REVIEW',
    SET_READY_FOR_CONTINUE: 'SET_READY_FOR_CONTINUE',
    SET_TRANSLATION: 'SET_TRANSLATION',
    SET_WRONG_RESULT: 'SET_WRONG_RESULT',
    SET_OPTIONS: 'SET_OPTIONS',
    SET_CORRECT_RESULT_ENABLED: 'SET_CORRECT_RESULT_ENABLED',
    SET_IS_START_PAGE: 'SET_IS_START_PAGE',
};

export default puzzleTypes;
